### ISSUE TITLE
TypeError from MaxPool2DLayer

### ISSUE THREAD

**Issue by oolongtea** [enlitic/lasagne4newbs#1]
Thanks for the well-commented example! Just wanted to bring it up in case someone else got a similar error.

I'm running Lasagne==0.1.dev and Theano==0.7.0.

The error is from MaxPool2DLayer:

```
    Traceback (most recent call last):
      File "conv.py", line 61, in <module>
        l_pool1 = lasagne.layers.MaxPool2DLayer(l_conv1, ds=(2, 2))
    TypeError: __init__() takes at least 3 arguments (2 given)
```

Changing `ds` to `pool_size` as specified in [`lasagne.pool.MaxPool2DLayer`](https://github.com/Lasagne/Lasagne/blob/30e91b877aa01e8854b6142e16c4c0bff0f21661/lasagne/layers/pool.py#L155) will fix this error.

**Comment by diogo149** [comment]
Thanks! Fixed in https://github.com/enlitic/lasagne4newbs/pull/2
